### ISSUE TITLE
Add deletedAt Field to Role, Channel, and Guild Member Schemas

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/mongo-lib#94]
### Description:
we want to implement a soft deletion mechanism. This requires adding a **deletedAt** field to our Role, Channel, and Guild Member schemas. This new field will store the timestamp of when an entity is considered "deleted", enabling easier tracking and potential recovery of deleted entries.

### Tasks to Implement:
- [ ]  Add deletedAt field to Role schema
- [ ]  Add deletedAt field to Channel schema
- [ ]  Add deletedAt field to Guild Member schema
